# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PCA_mod2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(788, 586)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(788, 586))
        MainWindow.setMaximumSize(QtCore.QSize(788, 586))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.midLine = QtWidgets.QFrame(self.centralwidget)
        self.midLine.setGeometry(QtCore.QRect(353, 10, 20, 531))
        self.midLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.midLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.midLine.setObjectName("midLine")
        self.projectListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.projectListWidget.setGeometry(QtCore.QRect(20, 40, 311, 501))
        self.projectListWidget.setLineWidth(1)
        self.projectListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.projectListWidget.setAlternatingRowColors(True)
        self.projectListWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.projectListWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.projectListWidget.setWordWrap(True)
        self.projectListWidget.setSelectionRectVisible(True)
        self.projectListWidget.setObjectName("projectListWidget")
        self.SubmitButton = QtWidgets.QPushButton(self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(680, 460, 91, 23))
        self.SubmitButton.setObjectName("SubmitButton")
        self.messageLog = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.messageLog.setGeometry(QtCore.QRect(380, 460, 291, 81))
        self.messageLog.setObjectName("messageLog")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(680, 490, 91, 23))
        self.clearButton.setObjectName("clearButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(680, 520, 91, 23))
        self.exitButton.setObjectName("exitButton")
        self.projectDetails = QtWidgets.QGroupBox(self.centralwidget)
        self.projectDetails.setGeometry(QtCore.QRect(380, 10, 401, 91))
        self.projectDetails.setObjectName("projectDetails")
        self.projDetailsLabel1 = QtWidgets.QLabel(self.projectDetails)
        self.projDetailsLabel1.setGeometry(QtCore.QRect(10, 20, 381, 16))
        self.projDetailsLabel1.setWordWrap(True)
        self.projDetailsLabel1.setObjectName("projDetailsLabel1")
        self.projDetailsLabel2 = QtWidgets.QLabel(self.projectDetails)
        self.projDetailsLabel2.setGeometry(QtCore.QRect(10, 37, 381, 16))
        self.projDetailsLabel2.setWordWrap(True)
        self.projDetailsLabel2.setObjectName("projDetailsLabel2")
        self.projDetailsLabel3 = QtWidgets.QLabel(self.projectDetails)
        self.projDetailsLabel3.setGeometry(QtCore.QRect(10, 54, 381, 16))
        self.projDetailsLabel3.setWordWrap(True)
        self.projDetailsLabel3.setObjectName("projDetailsLabel3")
        self.projDetailsLabel4 = QtWidgets.QLabel(self.projectDetails)
        self.projDetailsLabel4.setGeometry(QtCore.QRect(10, 71, 381, 16))
        self.projDetailsLabel4.setWordWrap(True)
        self.projDetailsLabel4.setObjectName("projDetailsLabel4")
        self.actionGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.actionGroup.setGeometry(QtCore.QRect(380, 120, 201, 201))
        self.actionGroup.setObjectName("actionGroup")
        self.archiveOption = QtWidgets.QRadioButton(self.actionGroup)
        self.archiveOption.setGeometry(QtCore.QRect(10, 30, 181, 17))
        self.archiveOption.setObjectName("archiveOption")
        self.deleteOption = QtWidgets.QRadioButton(self.actionGroup)
        self.deleteOption.setGeometry(QtCore.QRect(10, 60, 181, 17))
        self.deleteOption.setObjectName("deleteOption")
        self.saveOption = QtWidgets.QRadioButton(self.actionGroup)
        self.saveOption.setGeometry(QtCore.QRect(10, 90, 181, 17))
        self.saveOption.setObjectName("saveOption")
        self.NAoption = QtWidgets.QRadioButton(self.actionGroup)
        self.NAoption.setGeometry(QtCore.QRect(10, 120, 181, 17))
        self.NAoption.setObjectName("NAoption")
        self.updatesGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.updatesGroup.setGeometry(QtCore.QRect(600, 120, 181, 201))
        self.updatesGroup.setObjectName("updatesGroup")
        self.restrictedOption = QtWidgets.QCheckBox(self.updatesGroup)
        self.restrictedOption.setGeometry(QtCore.QRect(10, 30, 161, 21))
        self.restrictedOption.setObjectName("restrictedOption")
        self.cleanedOption = QtWidgets.QCheckBox(self.updatesGroup)
        self.cleanedOption.setGeometry(QtCore.QRect(10, 60, 161, 21))
        self.cleanedOption.setObjectName("cleanedOption")
        self.reviewedOption = QtWidgets.QCheckBox(self.updatesGroup)
        self.reviewedOption.setGeometry(QtCore.QRect(10, 90, 171, 21))
        self.reviewedOption.setObjectName("reviewedOption")
        self.notesText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.notesText.setGeometry(QtCore.QRect(380, 350, 401, 91))
        self.notesText.setObjectName("notesText")
        self.notesLabel = QtWidgets.QLabel(self.centralwidget)
        self.notesLabel.setGeometry(QtCore.QRect(390, 330, 47, 13))
        self.notesLabel.setObjectName("notesLabel")
        self.userTitle = QtWidgets.QLabel(self.centralwidget)
        self.userTitle.setGeometry(QtCore.QRect(30, 10, 31, 16))
        self.userTitle.setObjectName("userTitle")
        self.userLabel = QtWidgets.QLabel(self.centralwidget)
        self.userLabel.setGeometry(QtCore.QRect(70, 10, 191, 16))
        self.userLabel.setAutoFillBackground(True)
        self.userLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.userLabel.setText("")
        self.userLabel.setObjectName("userLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Network Cleaner"))
        self.SubmitButton.setText(_translate("MainWindow", "Submit Update"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.projectDetails.setTitle(_translate("MainWindow", "Selected Project Details"))
        self.actionGroup.setTitle(_translate("MainWindow", "Choose an action"))
        self.archiveOption.setText(_translate("MainWindow", "De-identify and archive folder"))
        self.deleteOption.setText(_translate("MainWindow", "Delete folder completely"))
        self.saveOption.setText(_translate("MainWindow", "De-identify and save folder"))
        self.NAoption.setText(_translate("MainWindow", "Do nothing to folder"))
        self.updatesGroup.setTitle(_translate("MainWindow", "Confirm updates"))
        self.restrictedOption.setText(_translate("MainWindow", "Project has restricted folder"))
        self.cleanedOption.setText(_translate("MainWindow", "R2: cleaned folder for action"))
        self.reviewedOption.setText(_translate("MainWindow", "R1: reviewed folder for action"))
        self.notesLabel.setText(_translate("MainWindow", "Notes:"))
        self.userTitle.setText(_translate("MainWindow", "User:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
